jobs: 32
cores: 10000
resources: [cap_slots=1]
local-cores: 1
cluster: "/gpfs/gibbs/project/dunn/cwd7/conda_envs/snakemake/bin/python profiles/slurm/submit.py"
cluster-status: "/gpfs/gibbs/project/dunn/cwd7/conda_envs/snakemake/bin/python profiles/slurm/status.py"
latency-wait: 180
rerun-incomplete: true
keep-going: true
printshellcmds: true
show-failed-logs: true
rerun-triggers: [mtime]
restart-times: 0
use-conda: true
conda-frontend: mamba
max-status-checks-per-second: 2
max-jobs-per-second: 2
